[package]
name = "broadcaster"
version = "0.1.0"
authors = ["leo60228 <iakornfeld@gmail.com>"]
edition = "2018"

[features]
default = ["default-channels"]
default-channels = ["futures-channel-preview"]

[dependencies]
futures-core-preview = "0.3.0-alpha.18"
futures-sink-preview = "0.3.0-alpha.18"
futures-util-preview = { version = "0.3.0-alpha.18", features = ["sink"] }
futures-channel-preview = { version = "0.3.0-alpha.18", optional = true, features = ["sink"] }

[dev-dependencies]
futures-executor-preview = "0.3.0-alpha.18"
